### ISSUE TITLE
active vscode session no longer prevents cloud9 instance from being shut down

### ISSUE THREAD

**Issue by qing-at-work** [aws-samples/cloud9-to-power-vscode-blog#3]
The cloud9 instance still shuts down automatically even with an active vscode session.
Looks like this might be caused by recent "Remote - SSH" extension update. It uses `bin/code-server` instead of `server.sh` to launch the container, so the `is_vscode_connected()` [check](https://github.com/aws-samples/cloud9-to-power-vscode-blog/blob/d0a7dbdf9f12494d3e7ee6151a9017e469705eb9/scripts/stop-if-inactive.sh#L44) is no longer able to find the vscode process.

**Comment by nragusa** [comment]
Thanks for the fix!
